export const RETRIEVE_ALL_MESSAGES = 'RETRIEVE_ALL_MESSAGES';
export const UPDATE_MESSAGE_STATUS = 'UPDATE_MESSAGE_STATUS';
export const PUSH_CUSTOMER_INFO = 'PUSH_CUSTOMER_INFO';
export const PUSH_ONLY_MESSAGE = 'PUSH_ONLY_MESSAGE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const UPDATE_NAME = 'UPDATE_NAME';
export const UPDATE_EMAIL = 'UPDATE_EMAIL';
export const UPDATE_PHONE = 'UPDATE_PHONE';